#!/bin/sh

apt-get -y install      \
        ruby \
        build-essential zlib1g zlib1g-dev       \
        libxml2 libxml2-dev libxslt-dev locate \
        libreadline6-dev libcurl4-openssl-dev git-core \
        libssl-dev libyaml-dev openssl autoconf libtool \
        ncurses-dev bison curl wget postgresql \
        postgresql-contrib libpq-dev \
        libapr1 libaprutil1 libsvn1 \
        libpcap-dev
