#!/bin/bash

init_para()
{
	PATH=$PATH:/usr/bin:/bin:/sbin:/usr/local/bin

	[ `id -u` -eq 0 ] || echo "Root previlige needed" && exit 1
}

# security check
secu_chk()
{
	rootpass=`grep root /etc/passwd | awk -F: '{print $2}'`
	if [ rootpass -ne x ]
	then
		echo "Root account doesn't has a valide password"
	fi
}

init_vim()
{
	cp /etc/vim/vimrc{.orig}
#	sed -i /etc/vim/vimrc
}

software_inst()
{
	apt-get update 
	apt-get upgrade
	apt-get install vim git-core
}
