#!/bin/bash

# link: http://ubuntuforums.org/showthread.php?t=835573

# Set thsi to the exact path of the nvidia driver you plan to use
# It is recommended to use a symlink here so that this script doesn't
# have to be modified when you change driver versions.

# Usage:
#	sudo mv NVIDIA-Linux-x86-173.14.05-pkg1.run /usr/src
#	sudo ln -s /usr/src/NVIDIA-Linux-x86-173.14.05-pkg1.run /usr/src/nvidia-driver
#	sudo mkdir -p /etc/kernel/postinst.d
#	sudo install update-nvidia /etc/kernel/postinst.d

DRIVER=/usr/src/nvidia-driver

# Build new driver if it doesn't exist
if [ -e /lib/modules/$1/kernel/drivers/video/nvidia.ko ]
then
	echo "NVIDIA driver already exists for this kernel." >&2
else
	echo "Building NVIDIA driver for kernel $1" >&2
	sh $DRIVER -K -k $1 -s -n 2>1 > /dev/null

	if [ -e /lib/modules/$1/kernel/drivers/video/nvidia.ko ]
	then
		echo "	SUCCESS: Driver installed for kernel $1" >&2
	else
		echo "	FAILED: See /var/log/nvidia-installer.log" >&2
	fi
fi

exit 0
