#!/bin/sh

# setup path {
PATH=$PATH:/usr/bin:/bin:/sbin:/usr/local/bin
[ $(id -u) -eq 0 ] || echo "root privilege needed" && exit 1
#}

# remove unused software
function remove_software() {
}

# update system
function system_update() {
	apt-get update
	apt-get upgrade
}

#security check
function enforce_security() {
	rootpass = $(grep root /etc/passwd | awk -F: '{print $2}')
	if [ rootpass -ne x ]; then
		echo "root password null"
	fi
}

#system config {
# disable guest account
echo "allow-guest=false" >> /etc/lightdm/lightdm.conf
# disable remote login
echo "greeter-show-remote-login=false" >> /etc/lightdm/lightdm.conf
#}

#software config {
# set gedit
gsettings set org.gnome.gedit.preferences.encodings auto-detected "['UTF-8', 'GB18030', 'GB2312', 'GBK', 'BIG5', 'CURRENT', 'ISO-8859-15', 'UTF-16']"
cp /etc/vim/vim73/vimrc_example ~/.vimrc
#}

# mp3 file name
export PATH=$PATH GST_ID3_TAG_ENCODING=GBK:UTF-8:GB18030
export PATH=$PATH GST_ID3V2_TAG_ENCODING=GBK:UTF-8:GB18030

# install skype
sudo apt-get install libxss1 libqtwebkit4
sudo dpkg -i skype*.deb

echo “安装必要软件”
p7zip
unrar 
flash-plugin-installer
vim-data
#vim
git-core

echo "字体配置"
mkfontdir
fc-cache -fv
